### ISSUE TITLE
ngtable-java/src/main/java/cz/nuc/ngtablejava/data/MemberFilterer.java:5

### ISSUE THREAD

**Issue by ghost** [MartinNuc/ngtable-java#1]
I have got a error: The import cz.nuc.ngtablejava.model.Member_ cannot be resolved.
So please do you have some advice?

**Comment by MartinNuc** [comment]
This means that your JPA model generator is not properly configured or that your IDE is not configured to look for sources in target/generated-sources.

Try to run mvn compile

It should generate stuff in target/generated-sources/annotations/... check if its present.

Afterwards you should specify in your IDE that it should look for generated sources in this directory.

**Comment by ghost** [comment]
That's awesome. But I got a 404 not found error when post to the ngtablejava/members/filter.
I have eclipse and tomcat to be my development tools. To debugging this project I need a jboss server, right?

**Comment by MartinNuc** [comment]
That means that JAX-RS is not working or that base url for that app is elsewhere. I dont have experience with Tomcat but usually its configured using XML. In JBoss its possible to start it up in code with this: https://github.com/mistm/ngtable-java/blob/master/src/main/java/cz/nuc/ngtablejava/rest/JaxRsActivator.java

However you should be able to run this on Tomcat if you get working some Hello World REST service.

After that you can call MemberRepository.filterItems() like in https://github.com/mistm/ngtable-java/blob/master/src/main/java/cz/nuc/ngtablejava/rest/MemberResourceRESTService.java
